# Huggingface demo
https://huggingface.co

`poetry add transformers`

In [7]:
# pipelines
from transformers import pipeline

classifier = pipeline("sentiment-analysis", model="distilbert-base-multilingual-cased")

Some weights of the model checkpoint at distilbert-base-multilingual-cased were not used when initializing DistilBertForSequenceClassification: ['vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_transform.weight', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.bias']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['pre_classifier.bias', 'classifie

In [11]:
classifier("I do not like this movie")

[{'label': 'LABEL_0', 'score': 0.512522280216217}]

In [13]:
# speech recognition
classifier = pipeline("automatic-speech-recognition", model="facebook/wav2vec2-base-960h")

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [14]:
classifier("./obama.mp3")

{'text': "O   IF I A TOLD YOU EIGHT YEARS AGO THAT AMERICA WOULD REVERSE O GRATE RESESSION WE BOOT OUR AUTOR IN HIS AND UNLEASH THE LONGEST TRETCH OF JO CREATION IN OUR HIS E CI TOLD  AND WE WOULD OPEN UP A NEW CHAPTER WITH THE CUBAN PEOPE SHUT DOWN ARONDS NECLY WEUP A COVER WITH U BIR AN SH A COUP O MASOR MINE A NINE A LU  O CO YO TO WE WOULD WEN TO MARRIA O CRALITY AND SE COO A ON IN ONG AN O  O FET O IF I TOL L THAT OU MIGHT HAVE SAID OUR SIGHTS WERE SET A LITTLE TOO HUT THAT'S WHAT WE DID A PEN DO THA AFTER MY ELECTION THERE WAS TALK OF A POST RATIAL AMERIC AND SUCH A VISION HOW OVER WELL INTENDED WAS NEVER REALISTEN RACE REMAINS A COLDEN AND OFFEN TO BISS OF FORCE IN OUR SOCIDETY IF YOU TIRE OF ARGUN WI STRANGERS ON IN AND IN TRY TALKING WUN ONE OF THEM IN REAL LIFE IT YO TISE CON IN TO BI YOUR ELET TO TH BISHOS GRABE TLED BOARD GETS AND SIGNATURES AND ONE CRO THESWO S SHO DIME IN STAY ATIT SOMETIMES YOU'LL WIN SOMETIMES YOU'LL LOOSE I SHEL WO PON OP AN SEN GIRL OF THE SOL SIN O M

In [5]:
# AUTO CLASS

from transformers import AutoTokenizer

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [7]:
encoding = tokenizer(["Hello the ones who are still here"], return_tensors="pt")
encoding

{'input_ids': tensor([[  101, 29155, 10103, 28573, 10488, 10320, 12440, 14048,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [16]:
encoding = tokenizer(["Hello the ones who are still here", "hello"], truncation=True, padding=True, max_length=128, return_tensors="pt")
encoding

{'input_ids': tensor([[  101, 29155, 10103, 28573, 10488, 10320, 12440, 14048,   102],
        [  101, 29155,   102,     0,     0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 0, 0, 0, 0, 0, 0]])}

In [14]:
from transformers import AutoModelForSequenceClassification

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
pt_model = AutoModelForSequenceClassification.from_pretrained(model_name)

In [18]:
outputs = pt_model(**encoding)

In [19]:
from torch import nn

nn.Softmax(dim=1)(outputs.logits)

tensor([[0.0777, 0.0386, 0.0776, 0.1614, 0.6447],
        [0.0977, 0.0494, 0.1111, 0.1803, 0.5614]], grad_fn=<SoftmaxBackward0>)

In [21]:
encoding = tokenizer(["Hi, this mac does not turn on :( Shitty product)", "THIS SWEATER IS AWESOME!!!!"], truncation=True, padding=True, max_length=128, return_tensors="pt")
outputs = pt_model(**encoding)
nn.Softmax(dim=1)(outputs.logits)

tensor([[0.8899, 0.0903, 0.0164, 0.0022, 0.0012],
        [0.0024, 0.0013, 0.0081, 0.0646, 0.9235]], grad_fn=<SoftmaxBackward0>)

In [22]:
from transformers import AutoModel

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
pt_model = AutoModel.from_pretrained(model_name)

Some weights of the model checkpoint at nlptown/bert-base-multilingual-uncased-sentiment were not used when initializing BertModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [26]:
outputs = pt_model(**encoding)
outputs[0].shape

torch.Size([2, 16, 768])

In [27]:
tokenizer.save_pretrained("my_tokenizer")

('my_tokenizer/tokenizer_config.json',
 'my_tokenizer/special_tokens_map.json',
 'my_tokenizer/vocab.txt',
 'my_tokenizer/added_tokens.json',
 'my_tokenizer/tokenizer.json')

In [28]:
# Using hugginface wit torch

In [39]:
import torch

class SomeModel(nn.Module):
    def __init__(self, model_name):
        super().__init__()
        self.feature_extractor = AutoModel.from_pretrained(model_name)
        self.classfier = nn.Linear(12288, 2)

    def forward(self, x) -> torch.Tensor:
        x = self.feature_extractor(**x)[0]
        x = x.view(x.shape[0], -1)
        return self.classfier(x)

In [42]:
some_model = SomeModel("nlptown/bert-base-multilingual-uncased-sentiment")

outputs = some_model(encoding)
print(outputs[0].shape)
outputs

Some weights of the model checkpoint at nlptown/bert-base-multilingual-uncased-sentiment were not used when initializing BertModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


torch.Size([2])


tensor([[-0.2675,  0.1361],
        [ 0.3143, -0.0458]], grad_fn=<AddmmBackward0>)

In [43]:
# Using trainer
from transformers import TrainingArguments
from datasets import load_dataset
from transformers import Trainer
from transformers import DataCollatorWithPadding

training_args = TrainingArguments(
    output_dir="path/to/save/folder/",
    learning_rate=2e-5,
    num_train_epochs=2,
)

model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased")
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

dataset = load_dataset("rotten_tomatoes")

def tokenize_dataset(dataset):
    return tokenizer(dataset["text"])

dataset = dataset.map(tokenize_dataset, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)


trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_transform.weight', 'vocab_layer_norm.weight', 'vocab_projector.weight', 'vocab_layer_norm.bias', 'vocab_transform.bias', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.weight', 'pre_classifier.weight', 'pre_clas

Dataset rotten_tomatoes downloaded and prepared to /Users/dqmis/.cache/huggingface/datasets/rotten_tomatoes/default/1.0.0/40d411e45a6ce3484deed7cc15b82a53dad9a72aafd9f86f8f227134bec5ca46. Subsequent calls will reuse this data.


100%|██████████| 3/3 [00:00<00:00, 1071.34it/s]


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [44]:
trainer.train()

/Users/dqmis/github/code_academy_ai_course/.venv/lib/python3.9/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


wandb: Currently logged in as: vinted_dqmis. Use `wandb login --relogin` to force relogin


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


  6%|▋         | 134/2134 [00:37<09:08,  3.64it/s]

KeyboardInterrupt: 